MLIR: lib/Dialect/Bufferization/Transforms/Bufferize.cpp File Reference
Bufferize.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Bufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/Passes.h"
Classes
struct BufferizationPattern
Rewrite pattern that bufferizes bufferizable ops.
Functions
static Value materializeToTensor (OpBuilder &builder, TensorType type, ValueRange inputs, Location loc)
static bool isaTensor (Type t)
static bool hasTensorSemantics (Operation *op)
Return true if the given op has a tensor result or a tensor operand.
static LogicalResult checkBufferizationResult (Operation *op, const BufferizationOptions &options)
Check the result of bufferization.
Function Documentation
checkBufferizationResult()
static LogicalResult checkBufferizationResult (Operation * op, const BufferizationOptions & options) static
Check the result of bufferization.
Return an error if an op was not bufferized, unless partial bufferization is allowed.
Definition at line 272 of file Bufferize.cpp.
References mlir::WalkResult::advance(), mlir::bufferization::BufferizationOptions::allowUnknownOps, mlir::Operation::emitError(), mlir::failed(), mlir::Operation::getUses(), hasTensorSemantics(), mlir::WalkResult::interrupt(), mlir::bufferization::BufferizationOptions::isOpAllowed(), mlir::success(), and mlir::Operation::walk().
Referenced by mlir::bufferization::bufferizeOp().
hasTensorSemantics()
static bool hasTensorSemantics (Operation * op) static
Return true if the given op has a tensor result or a tensor operand.
Definition at line 239 of file Bufferize.cpp.
References mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), and isaTensor().
Referenced by checkBufferizationResult(), and BufferizationPattern::matchAndRewrite().
isaTensor()
static bool isaTensor (Type t) static
Definition at line 236 of file Bufferize.cpp.
References mlir::Type::isa().
Referenced by hasTensorSemantics().
materializeToTensor()
static Value materializeToTensor (OpBuilder & builder, TensorType type, ValueRange inputs, Location loc) static
Definition at line 29 of file Bufferize.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::bufferization::BufferizeTypeConverter::BufferizeTypeConverter().