MLIR: lib/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.cpp File Reference
ModuleBufferization.cpp File Reference
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Bufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/Operation.h"
Classes
struct mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface
struct mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface
struct mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface
Namespaces
mlir
Include the generated interface declarations.
mlir::linalg
mlir::linalg::comprehensive_bufferize
mlir::linalg::comprehensive_bufferize::std_ext
Typedefs
using FuncCallerMap = DenseMap< func::FuncOp, DenseSet< Operation * > >
A mapping of FuncOps to their callers.
Enumerations
enum FuncOpAnalysisState
The state of analysis of a FuncOp.
Functions
static const FuncAnalysisState & getFuncAnalysisState (const AnalysisState &state)
Get FuncAnalysisState.
static FuncAnalysisState & getFuncAnalysisState (AnalysisState &state)
Get or create FuncAnalysisState.
static FuncOpAnalysisState getFuncOpAnalysisState (const AnalysisState &state, func::FuncOp funcOp)
Return the state (phase) of analysis of the FuncOp.
static func::ReturnOp getAssumedUniqueReturnOp (func::FuncOp funcOp)
Return the unique ReturnOp that terminates funcOp.
static bool isaTensor (Type t)
static Value getNonCastedValue (Value value)
If value is a memref::CastOp, return its source.
static void removeBufferizationFuncArguments (BlockArgument bbArg)
Remove the attribute that triggers inplace bufferization on a func::FuncOp argument bbArg.
static func::FuncOp getCalledFunction (CallOpInterface callOp)
Return the func::FuncOp called by callOp.
static FunctionType getBufferizedFunctionType (MLIRContext *ctx, TypeRange argumentTypes, TypeRange resultTypes, const BufferizationOptions &options)
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
static void equivalenceAnalysis (func::FuncOp funcOp, BufferizationAliasInfo &aliasInfo, FuncAnalysisState &funcState)
Gather equivalence info of CallOps.
static LogicalResult bufferizeFuncOpBoundary (func::FuncOp funcOp, RewriterBase &rewriter, BufferizationState &state)
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< func::FuncOp > &orderedFuncOps, FuncCallerMap &callerMap)
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
static void foreachCaller (const FuncCallerMap &callerMap, func::FuncOp callee, llvm::function_ref< void(Operation *)> doit)
static void layoutPostProcessing (ModuleOp moduleOp)
Postprocess the linalg.buffer_layout annotation across function boundaries.
static Optional< int64_t > mlir::linalg::comprehensive_bufferize::std_ext::getEquivalentFuncArgIdx (func::FuncOp funcOp, const FuncAnalysisState &state, int64_t returnValIdx)
Return the index of the bbArg in the given func::FuncOp that is equivalent to the specified return value (if any).
static void setInPlaceFuncArgument (BlockArgument bbArg, bool inPlace)
Set the attribute that triggers inplace bufferization on a func::FuncOp argument bbArg.
static void annotateOpsWithBufferizationMarkers (func::FuncOp funcOp, const AnalysisState &state)
Annotate the IR with the result of the analysis. For testing/debugging only.
Typedef Documentation
FuncCallerMap
using FuncCallerMap = DenseMap<func::FuncOp, DenseSet<Operation *> >
A mapping of FuncOps to their callers.
Definition at line 90 of file ModuleBufferization.cpp.
Enumeration Type Documentation
FuncOpAnalysisState
enum FuncOpAnalysisState strong
The state of analysis of a FuncOp.
Definition at line 94 of file ModuleBufferization.cpp.
Function Documentation
annotateOpsWithBufferizationMarkers()
static void annotateOpsWithBufferizationMarkers (func::FuncOp funcOp, const AnalysisState & state) static
Annotate the IR with the result of the analysis. For testing/debugging only.
Definition at line 1053 of file ModuleBufferization.cpp.
References setInPlaceFuncArgument().
Referenced by mlir::linalg::comprehensive_bufferize::runModuleBufferize().
bufferizeFuncOpBoundary()
static LogicalResult bufferizeFuncOpBoundary (func::FuncOp funcOp, RewriterBase & rewriter, BufferizationState & state) static
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
This relies on a buffer equivalence analysis of each return operand. When a result buffer is equivalent to a BlockArgument of funcOp, it can be dropped from the return values and becomes inplaceable at all callers. This assumes all CallOp perform the necessary work to clone operands so as to make them inplaceable. Reliance on this logic will need to be relaxed in the future.
Note: Returning a memref currently fails bufferization. If such memrefs originate from an op with an Alloc effect, they could be hoisted in the future.
Definition at line 432 of file ModuleBufferization.cpp.
References mlir::Block::addArgument(), mlir::Type::dyn_cast(), mlir::Block::eraseArgument(), mlir::Block::front(), mlir::bufferization::BufferizationState::getAnalysisState(), mlir::Block::getArgument(), mlir::Block::getArguments(), getAssumedUniqueReturnOp(), mlir::bufferization::BufferizationState::getBuffer(), getBufferizedFunctionType(), getFuncAnalysisState(), getNonCastedValue(), mlir::Block::getNumArguments(), mlir::bufferization::BufferizationState::getOptions(), mlir::Value::getType(), mlir::Type::isa(), isaTensor(), mlir::Value::replaceAllUsesWith(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
Referenced by mlir::linalg::comprehensive_bufferize::runModuleBufferize().
equivalenceAnalysis()
static void equivalenceAnalysis (func::FuncOp funcOp, BufferizationAliasInfo & aliasInfo, FuncAnalysisState & funcState) static
Gather equivalence info of CallOps.
Note: This only adds new equivalence info if the called function was already analyzed.
Definition at line 395 of file ModuleBufferization.cpp.
References mlir::WalkResult::advance(), getCalledFunction(), mlir::WalkResult::skip(), and mlir::bufferization::BufferizationAliasInfo::unionEquivalenceClasses().
Referenced by mlir::linalg::comprehensive_bufferize::runModuleBufferize().
foreachCaller()
static void foreachCaller (const FuncCallerMap & callerMap, func::FuncOp callee, llvm::function_ref< void(Operation *)> doit) static
Definition at line 619 of file ModuleBufferization.cpp.
getAssumedUniqueReturnOp()
static func::ReturnOp getAssumedUniqueReturnOp (func::FuncOp funcOp) static
Return the unique ReturnOp that terminates funcOp.
Return nullptr if there is no such unique ReturnOp.
Definition at line 189 of file ModuleBufferization.cpp.
References mlir::bufferization::BufferizationAliasInfo::applyOnAliases(), mlir::bufferization::BufferizationAliasInfo::areAliasingBufferizedValues(), mlir::bufferization::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::bufferization::AnalysisState::bufferizesToMemoryWrite(), mlir::Attribute::cast(), mlir::Value::dyn_cast(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::BlockArgument::getArgNumber(), mlir::Operation::getAttr(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), getFuncAnalysisState(), getFuncOpAnalysisState(), mlir::Operation::getNumOperands(), mlir::OpOperand::getOperandNumber(), mlir::bufferization::AnalysisState::getOptions(), mlir::detail::IROperandBase::getOwner(), mlir::BlockArgument::getOwner(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), mlir::Value::getType(), mlir::Value::getUses(), mlir::Operation::hasAttr(), mlir::Type::isa(), mlir::bufferization::AnalysisState::isInPlace(), mlir::bufferization::AnalysisState::isValueRead(), mlir::Operation::setAttr(), mlir::success(), mlir::bufferization::BufferizationOptions::testAnalysisOnly, and value.
Referenced by bufferizeFuncOpBoundary().
getBufferizedFunctionType()
static FunctionType getBufferizedFunctionType (MLIRContext * ctx, TypeRange argumentTypes, TypeRange resultTypes, const BufferizationOptions & options) static
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
In order for all the callers to agree, this must bufferize to the most dynamic buffer type supported. A later pass across all CallOps in the module can decide whether to simplify the types of to version according to some cost model.
Definition at line 376 of file ModuleBufferization.cpp.
References mlir::bufferization::getMemRefType(), and rewrite().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), and bufferizeFuncOpBoundary().
getCalledFunction()
static func::FuncOp getCalledFunction (CallOpInterface callOp) static
Return the func::FuncOp called by callOp.
Definition at line 361 of file ModuleBufferization.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryRead(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryWrite(), equivalenceAnalysis(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpOperand(), and mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpResult().
getFuncAnalysisState() [1/2]
static const FuncAnalysisState& getFuncAnalysisState (const AnalysisState & state) static
Get FuncAnalysisState.
Definition at line 163 of file ModuleBufferization.cpp.
References mlir::bufferization::AnalysisState::getDialectState().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), bufferizeFuncOpBoundary(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryRead(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryWrite(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpOperand(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpResult(), getAssumedUniqueReturnOp(), getFuncOpAnalysisState(), and mlir::linalg::comprehensive_bufferize::runModuleBufferize().
getFuncAnalysisState() [2/2]
static FuncAnalysisState& getFuncAnalysisState (AnalysisState & state) static
Get or create FuncAnalysisState.
Definition at line 172 of file ModuleBufferization.cpp.
References mlir::bufferization::AnalysisState::getOrCreateDialectState().
getFuncOpAnalysisState()
static FuncOpAnalysisState getFuncOpAnalysisState (const AnalysisState & state, func::FuncOp funcOp) static
Return the state (phase) of analysis of the FuncOp.
Definition at line 178 of file ModuleBufferization.cpp.
References getFuncAnalysisState().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryRead(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryWrite(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpOperand(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpResult(), and getAssumedUniqueReturnOp().
getFuncOpsOrderedByCalls()
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< func::FuncOp > & orderedFuncOps, FuncCallerMap & callerMap) static
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
callees without callers first). Store the map of FuncOp to all its callers in callerMap. Return failure() if a cycle of calls is detected or if we are unable to retrieve the called FuncOp from any CallOpInterface.
Definition at line 568 of file ModuleBufferization.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::runModuleBufferize().
getNonCastedValue()
static Value getNonCastedValue (Value value) static
If value is a memref::CastOp, return its source.
Otherwise, return value directly.
Definition at line 344 of file ModuleBufferization.cpp.
References mlir::Value::getDefiningOp(), and value.
Referenced by bufferizeFuncOpBoundary().
isaTensor()
static bool isaTensor (Type t) static
Definition at line 340 of file ModuleBufferization.cpp.
References mlir::Type::isa().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), and bufferizeFuncOpBoundary().
layoutPostProcessing()
static void layoutPostProcessing (ModuleOp moduleOp) static
Postprocess the linalg.buffer_layout annotation across function boundaries.
This is a purely mechanical process that may later become part of a separate pass with its own layout assignment heuristic.
Definition at line 631 of file ModuleBufferization.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::runModuleBufferize().
removeBufferizationFuncArguments()
static void removeBufferizationFuncArguments (BlockArgument bbArg) static
Remove the attribute that triggers inplace bufferization on a func::FuncOp argument bbArg.
Definition at line 352 of file ModuleBufferization.cpp.
References mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by mlir::linalg::comprehensive_bufferize::runModuleBufferize().
setInPlaceFuncArgument()
static void setInPlaceFuncArgument (BlockArgument bbArg, bool inPlace) static
Set the attribute that triggers inplace bufferization on a func::FuncOp argument bbArg.
Definition at line 1045 of file ModuleBufferization.cpp.
References mlir::BoolAttr::get(), mlir::BlockArgument::getArgNumber(), mlir::Value::getContext(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by annotateOpsWithBufferizationMarkers().