MLIR: mlir::linalg::comprehensive_bufferize::std_ext Namespace Reference
mlir::linalg::comprehensive_bufferize::std_ext Namespace Reference
Classes
struct CallOpInterface
struct FuncOpInterface
struct ReturnOpInterface
Functions
void registerModuleBufferizationExternalModels (DialectRegistry &registry)
static Optional< int64_t > getEquivalentFuncArgIdx (func::FuncOp funcOp, const FuncAnalysisState &state, int64_t returnValIdx)
Return the index of the bbArg in the given func::FuncOp that is equivalent to the specified return value (if any).
Function Documentation
getEquivalentFuncArgIdx()
static Optional<int64_t> mlir::linalg::comprehensive_bufferize::std_ext::getEquivalentFuncArgIdx (func::FuncOp funcOp, const FuncAnalysisState & state, int64_t returnValIdx) static
Return the index of the bbArg in the given func::FuncOp that is equivalent to the specified return value (if any).
Definition at line 723 of file ModuleBufferization.cpp.
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize().
registerModuleBufferizationExternalModels()
void mlir::linalg::comprehensive_bufferize::std_ext::registerModuleBufferizationExternalModels (DialectRegistry & registry)
Definition at line 1035 of file ModuleBufferization.cpp.
References mlir::DialectRegistry::addExtension().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface::isAllocationHoistingBarrier().