MLIR: mlir::linalg::comprehensive_bufferize Namespace Reference
mlir::linalg::comprehensive_bufferize Namespace Reference
Namespaces
std_ext
Functions
LogicalResult runModuleBufferize (ModuleOp moduleOp, bufferization::OneShotBufferizationOptions options)
Run Module Bufferization on the given module.
Function Documentation
runModuleBufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::runModuleBufferize (ModuleOp moduleOp, bufferization::OneShotBufferizationOptions options)
Run Module Bufferization on the given module.
Performs a simple function call analysis to determine which function arguments are inplaceable. Then analyzes and bufferizes FuncOps one-by-one with One-Shot Bufferize.
Definition at line 1061 of file ModuleBufferization.cpp.
References mlir::bufferization::OneShotBufferizationOptions::addPostAnalysisStep(), mlir::bufferization::OneShotBufferizationOptions::allowReturnAllocs, mlir::bufferization::analyzeOp(), annotateOpsWithBufferizationMarkers(), bufferizeFuncOpBoundary(), mlir::bufferization::bufferizeOp(), equivalenceAnalysis(), mlir::failed(), mlir::failure(), mlir::bufferization::finalizeBuffers(), getFuncAnalysisState(), getFuncOpsOrderedByCalls(), layoutPostProcessing(), removeBufferizationFuncArguments(), mlir::success(), and mlir::bufferization::BufferizationOptions::testAnalysisOnly.
Referenced by allocationFnUsingAlloca().