MLIR: mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, const AnalysisState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, const AnalysisState &state) const
SmallVector< OpResult > getAliasingOpResult (Operation *op, OpOperand &opOperand, const AnalysisState &state) const
SmallVector< OpOperand * > getAliasingOpOperand (Operation *op, OpResult opResult, const AnalysisState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const AnalysisState &state) const
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, BufferizationState &state) const
In a first approximation, all the function arguments of a func::FuncOp are marked inplaceable.
Detailed Description
Definition at line 739 of file ModuleBufferization.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize (Operation * op, RewriterBase & rewriter, BufferizationState & state) const inline
In a first approximation, all the function arguments of a func::FuncOp are marked inplaceable.
For now, it is the responsibility of the callOp bufferization to allow func::FuncOp that are inplaceable to write inPlace.
Definition at line 832 of file ModuleBufferization.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::bufferization::BufferizationState::getAnalysisState(), mlir::bufferization::BufferizationState::getBuffer(), getBufferizedFunctionType(), getCalledFunction(), mlir::linalg::comprehensive_bufferize::std_ext::getEquivalentFuncArgIdx(), getFuncAnalysisState(), mlir::bufferization::BufferizationState::getOptions(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::Type::isa(), isaTensor(), options, mlir::bufferization::replaceOpWithBufferizedValues(), mlir::Operation::setAttrs(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, const AnalysisState & state) const inline
Definition at line 742 of file ModuleBufferization.cpp.
References getCalledFunction(), getFuncAnalysisState(), getFuncOpAnalysisState(), and mlir::OpOperand::getOperandNumber().
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, const AnalysisState & state) const inline
Definition at line 757 of file ModuleBufferization.cpp.
References getCalledFunction(), getFuncAnalysisState(), getFuncOpAnalysisState(), and mlir::OpOperand::getOperandNumber().
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferRelation (Operation * op, OpResult opResult, const AnalysisState & state) const inline
Definition at line 824 of file ModuleBufferization.cpp.
getAliasingOpOperand()
SmallVector<OpOperand *> mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpOperand (Operation * op, OpResult opResult, const AnalysisState & state) const inline
Definition at line 799 of file ModuleBufferization.cpp.
References getCalledFunction(), getFuncAnalysisState(), getFuncOpAnalysisState(), mlir::Operation::getOpOperands(), and mlir::OpResult::getResultNumber().
getAliasingOpResult()
SmallVector<OpResult> mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, const AnalysisState & state) const inline
Definition at line 772 of file ModuleBufferization.cpp.
References getCalledFunction(), getFuncAnalysisState(), getFuncOpAnalysisState(), mlir::OpOperand::getOperandNumber(), and mlir::Operation::getOpResults().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.cpp