MLIR: mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface Struct Reference
Public Member Functions
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, BufferizationState &state) const
bool isWritable (Operation *op, Value value, const AnalysisState &state) const
Return true if the given function argument is writable.
bool isAllocationHoistingBarrier (Operation *op) const
Detailed Description
Definition at line 1000 of file ModuleBufferization.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface::bufferize (Operation * op, RewriterBase & rewriter, BufferizationState & state) const inline
Definition at line 1003 of file ModuleBufferization.cpp.
References mlir::failure().
isAllocationHoistingBarrier()
bool mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface::isAllocationHoistingBarrier (Operation * op) const inline
Definition at line 1026 of file ModuleBufferization.cpp.
References mlir::linalg::comprehensive_bufferize::std_ext::registerModuleBufferizationExternalModels().
isWritable()
bool mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface::isWritable (Operation * op, Value value, const AnalysisState & state) const inline
Return true if the given function argument is writable.
Definition at line 1009 of file ModuleBufferization.cpp.
References mlir::Value::dyn_cast().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.cpp